ci:
  autoupdate_schedule: quarterly
  skip:
    - copyright
    - helm-lock
    - helmlint
    - ripsecrets
    - helm-template-gen

    - jsonschema-validator
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
      - id: check-toml
      - id: check-yaml
        exclude: ^templates/.+\.yaml$
        args:
          - --allow-multiple-documents
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/sbrunner/hooks
    rev: 0.5.0
    hooks:
      - id: copyright
      - id: workflows-require-timeout
      - id: helm-lock
  - repo: https://github.com/camptocamp/helm-common
    rev: 0.7.1
    hooks:
      - id: helm-template-gen
        files: |-
          (?x)(
            ^templates/.*$
            |^values\.yaml$
            |^Chart\.yaml$
            |^tests/values\.yaml$
          )
        args:
          - --values=tests/values.yaml
          - custom
          - .
          - tests/expected.yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.2
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.0.2 # npm
          - prettier-plugin-sh@0.13.1 # npm
          - prettier-plugin-toml@0.4.0 # npm
          - '@prettier/plugin-xml@0.12.0' # npm
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: git-check
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.24.1
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
      - id: check-jsonschema
        name: Check GitHub Workflows set timeout-minutes
        files: ^\.github/workflows/[^/]+$
        types:
          - yaml
        args:
          - --builtin-schema
          - github-workflows-require-timeout
      - id: check-renovate
        additional_dependencies:
          - pyjson5==1.6.4 # pypi
  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.5
    hooks:
      - id: ripsecrets
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.22
    hooks:
      - id: helmlint
  - repo: https://github.com/sbrunner/jsonschema-validator
    rev: 0.1.0
    hooks:
      - id: jsonschema-validator
        files: ^ci/config\.yaml$
