repos:
  - repo: https://github.com/sbrunner/jsonschema2md
    rev: 1.3.0
    hooks:
      - id: jsonschema2md
        files: values.schema.json
        args:
          - --pre-commit
          - values.schema.json
          - values.md
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-ast
      - id: debug-statements
      - id: check-toml
      - id: check-yaml
        exclude: ^templates/.+\.yaml$
        args:
          - --allow-multiple-documents
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/sbrunner/hooks
    rev: 1.4.1
    hooks:
      - id: copyright
      - id: workflows-require-timeout
      - id: helm-lock
      - id: canonicalize
  - repo: https://github.com/camptocamp/helm-common
    rev: 2.0.1
    hooks:
      - id: helm-template-gen
        files: |-
          (?x)(
            ^templates/.*$
            |^values\.yaml$
            |^Chart\.yaml$
            |^tests/values\.yaml$
          )
        args:
          - --values=tests/values.yaml
          - example
          - .
          - tests/expected.yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args:
          - --ignore-words=.github/spell-ignore-words.txt
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.5 # npm
          - prettier-plugin-sh@0.14.0 # npm
          - prettier-plugin-toml@2.0.1 # npm
          - '@prettier/plugin-xml@0.12.0' # npm
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: git-check
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.4
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
      - id: check-jsonschema
        name: Check GitHub Workflows set timeout-minutes
        files: ^\.github/workflows/[^/]+$
        types:
          - yaml
        args:
          - --builtin-schema
          - github-workflows-require-timeout
  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.8
    hooks:
      - id: ripsecrets
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.25
    hooks:
      - id: helmlint
  - repo: https://github.com/sbrunner/jsonschema-validator
    rev: 1.0.0
    hooks:
      - id: jsonschema-validator
        files: |-
          (?x)^(
            \.github/ghci\.yaml
            |\.github/publish\.yaml
          )$
  - repo: https://github.com/mheap/json-schema-spell-checker
    rev: main
    hooks:
      - id: json-schema-spell-checker
        files: ^values\.schema\.json$
        args:
          - --fields=description,title
          - --spelling=.github/spell-ignore-words.txt
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 40.0.4
    hooks:
      - id: renovate-config-validator
