{{- if hasKey .Values "clusterRole" }}
{{- with .Values.clusterRole }}
{{- if or ( not ( hasKey . "enabled" ) ) .enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .name | default (include "common.fullname" ( dict "root" $ "service" . ) ) }}
  {{- include "common.metadata" ( dict "root" $ "service" . ) | nindent 2 }}
rules:
{{- range .rules }}
  - apiGroups:
    {{- range .apiGroups }}
      - {{ . | quote }}
    {{- end }}
    resources:
    {{- range .resources }}
      - {{ . | quote }}
    {{- end }}
    verbs:
    {{- range .verbs }}
      - {{ . | quote }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
