apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values ) | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels: {{- include "common.selectorLabels" ( dict "root" . "service" .Values ) | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.selectorLabels" ( dict "root" . "service" .Values ) | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec: {{- include "common.podConfig" ( dict "root" . "service" .Values ) | indent 6 }}
      {{- if .Values.initContainers }}
      initContainers:
      {{- range $name, $config := .Values.initContainers }}
        - name: {{ $name }}
          {{- include "common.containerConfig" ( dict "root" $ "container" $config ) | nindent 10 }}
          {{- with $config.command }}
          command: {{ $config.command | toYaml | nindent 12 }}
          {{- end }}
          {{- with $config.args }}
          args: {{ $config.args | toYaml | nindent 12 }}
          {{- end }}
          {{- with $config.volumeMounts }}
          volumeMounts: {{ $config.volumeMounts | toYaml | nindent 12 }}
          {{- end }}
      {{- end }}
      {{- end }}
      containers:
      {{- range $name, $config := .Values.containers }}
        - name: {{ $name }}
          {{- include "common.containerConfig" ( dict "root" $ "container" $config ) | nindent 10 }}
          {{- with $config.command }}
          command:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with $config.args }}
          args:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with $config.volumeMounts }}
          volumeMounts:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with $config.ports }}
          ports:
            {{- $config.ports | toYaml | nindent 12 }}
          {{- end }}
          {{- with $config.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $config.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $config.readinessProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
