{{- $root := . -}}
{{- $values := .Values -}}

{{- range $serviceName, $serviceDefinition := $values.services }}
{{- if eq $serviceDefinition.enabled true }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" ( dict "root" $root "service" $serviceDefinition "serviceName" $serviceName ) }}
  {{- include "common.metadata" ( dict "root" $root "service" $serviceDefinition "serviceName" $serviceName ) | nindent 2 }}
spec:
  replicas: {{ $serviceDefinition.replicaCount | default 1 }}
  revisionHistoryLimit: {{ $values.global.revisionHistoryLimit | default 3 }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels: {{- include "common.selectorLabels" ( dict "root" $root "service" $serviceDefinition "serviceName" $serviceName ) | nindent 6 }}
  template:
    metadata: {{- include "common.podMetadata" ( dict "root" $root "service" $serviceDefinition "serviceName" $serviceName ) | nindent 6 }}
    spec:
      {{- include "common.podConfig" ( dict "root" $root "service" $serviceDefinition "serviceName" $serviceName ) | nindent 6 }}
      {{- if and (hasKey $serviceDefinition "initContainers") ($serviceDefinition.initContainers) }}
      initContainers:
      {{- range $name, $config := $serviceDefinition.initContainers }}
        - name: {{ $name }}
          {{- include "common.containerConfig" ( dict "root" $ "container" $config ) | nindent 10 }}
          {{- with $config.command }}
          command: {{ $config.command | toYaml | nindent 12 }}
          {{- end }}
          {{- with $config.args }}
          args: {{ $config.args | toYaml | nindent 12 }}
          {{- end }}
          {{- with $config.volumeMounts }}
          volumeMounts:
          {{- include "common.dictToList" ( dict "keyName" "mountPath" "contents" . ) | nindent 12 -}}
          {{- end -}}
      {{- end }}
      {{- end }}
      containers:
      {{- range $name, $config := $serviceDefinition.containers }}
        - name: {{ $name }}
          {{- include "common.containerConfig" ( dict "root" $ "container" $config ) | nindent 10 }}
          {{- with $config.command }}
          command:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with $config.args }}
          args:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with $config.volumeMounts }}
          volumeMounts:
          {{- include "common.dictToList" ( dict "keyName" "mountPath" "contents" . ) | nindent 12 -}}
          {{- end -}}
          {{- with $config.ports }}
          ports:
          {{- include "common.dictToList" ( dict "contents" . ) | nindent 12 -}}
          {{- end -}}
          {{- with $config.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $config.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $config.readinessProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      {{- with $serviceDefinition.volumes }}
      volumes:
      {{- include "common.dictToList" ( dict "contents" . ) | nindent 8 -}}
      {{- end }}
{{- end }}
{{- end }}
