{{- range $serviceName, $serviceDefinition := .Values.services }}
{{- if eq $serviceDefinition.enabled true }}
{{- if eq ( default "Deployment" $serviceDefinition.type ) "Deployment" }}
---
apiVersion: apps/v1
kind: {{ $serviceDefinition.type | default "Deployment" }}
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" $serviceDefinition "serviceName" $serviceName ) }}
  {{- include "common.metadata" ( dict "root" $ "service" $serviceDefinition "serviceName" $serviceName ) | nindent 2 }}
spec:
  {{- if $serviceDefinition.replicaCount }}
  replicas: {{ $serviceDefinition.replicaCount }}
  {{- end }}
  {{- if $serviceDefinition.replicas }}
  replicas: {{ $serviceDefinition.replicas }}
  {{- end }}
  revisionHistoryLimit: {{ $.Values.global.revisionHistoryLimit | default 0 }}
  strategy:
    type: {{ ( default $serviceDefinition.strategy dict ).type | default "RollingUpdate" }}
    {{- with ( default $serviceDefinition.strategy dict ).rollingUpdate }}
    rollingUpdate: {{ toYaml . | nindent 8 }}
    {{- end }}
  {{- if $serviceDefinition.progressDeadlineSeconds }}
  progressDeadlineSeconds: {{ $serviceDefinition.progressDeadlineSeconds }}
  {{- end }}
  {{- if $serviceDefinition.minReadySeconds }}
  minReadySeconds: {{ $serviceDefinition.minReadySeconds }}
  {{- end }}
  {{- if $serviceDefinition.paused }}
  paused: {{ $serviceDefinition.paused }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.selectorLabels" ( dict "root" $ "service" $serviceDefinition "serviceName" $serviceName ) | nindent 6 }}
  template:
    metadata: {{- include "application.podMetadata" ( dict "root" $ "service" $serviceDefinition "serviceName" $serviceName ) | nindent 6 }}
    spec:
      {{- include "application.podConfig" ( dict "root" $ "service" $serviceDefinition "serviceName" $serviceName ) | nindent 6 }}
      {{- with $serviceDefinition.restartPolicy }}
      restartPolicy: {{ . }}
      {{- end }}
      {{- if and (hasKey $serviceDefinition "initContainers") ($serviceDefinition.initContainers) }}
      initContainers:
      {{- range $name, $config := $serviceDefinition.initContainers }}
        - name: {{ $name }}
          {{- include "application.containerConfig" ( dict "root" $ "container" $config ) | nindent 10 }}
          {{- with $config.command }}
          command: {{ . | toYaml | nindent 12 }}
          {{- end }}
          {{- with $config.args }}
          args: {{ . | toYaml | nindent 12 }}
          {{- end }}
          {{- with $config.volumeMounts }}
          volumeMounts:
          {{- include "common.dictToList" ( dict "keyName" "mountPath" "contents" . ) | nindent 12 }}
          {{- end }}
          {{- with $config.volumeDevices }}
          volumeDevices:
          {{- include "common.dictToList" ( dict "keyName" "devicePath" "contents" . ) | nindent 12 }}
          {{- end }}
      {{- end }}
      {{- end }}
      containers:
      {{- range $name, $config := $serviceDefinition.containers }}
        - name: {{ $name }}
          {{- include "application.containerConfig" ( dict "root" $ "container" $config ) | nindent 10 }}
          {{- with $config.command }}
          command:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with $config.args }}
          args:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with $config.volumeMounts }}
          volumeMounts:
          {{- include "common.dictToList" ( dict "keyName" "mountPath" "contents" . ) | nindent 12 }}
          {{- end }}
          {{- with $config.volumeDevices }}
          volumeDevices:
          {{- include "common.dictToList" ( dict "keyName" "devicePath" "contents" . ) | nindent 12 }}
          {{- end }}
          {{- with $config.ports }}
          ports:
          {{- include "common.dictToList" ( dict "contents" . ) | nindent 12 }}
          {{- end }}
          {{- with $config.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $config.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $config.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $config.workingDir }}
          workingDir: {{ . }}
          {{- end }}
      {{- end }}
      {{- include "application.volumes" ( dict "root" $ "service" $serviceDefinition ) | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}
