{{- range $name, $definition := .Values.externalSecrets }}
{{- if or ( not ( hasKey $definition "enabled" ) ) $definition.enabled }}
{{- if ( or $definition.data $definition.dataFrom ) }}
---
{{- if ( and .Capabilities .Capabilities.APIVersions ( .Capabilities.APIVersions.Has "external-secrets.io/v1" ) ) }}
apiVersion: external-secrets.io/v1
{{- else }}
apiVersion: external-secrets.io/v1beta1
{{- end }}
kind: ExternalSecret
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" $definition "serviceName" $name ) }}
  {{- include "common.metadata" ( dict "root" $ "service" $definition "serviceName" $name ) | nindent 2 }}
spec:
  {{- with $definition.refreshInterval }}
  refreshInterval: {{ . }}
  {{- end }}
  {{- with $definition.secretStoreRef }}
  secretStoreRef: {{- toYaml . | nindent 4 }}
  {{- end }}
  target:
    {{- if not ( hasKey ( default ( dict ) .target ) "name" ) }}
    name: {{ include "common.fullname" ( dict "root" $ "service" $definition "serviceName" $name ) }}
    {{- end }}
    {{- with $definition.target }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $definition.dataFrom }}
  dataFrom: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $definition.data }}
  data: {{- include "common.dictToList" ( dict "keyName" "secretKey" "contents" . ) | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
