{{- with .Values.dockerregistry }}
{{- if .enabled }}
{{- if .external }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" . "serviceName" "docker-registry" ) }}
  {{- include "common.metadata" ( dict "root" $ "service" . ) | nindent 2 }}
spec:
  {{- with .refreshInterval }}
  refreshInterval: {{ . }}
  {{- end }}
  {{- with .secretStoreRef }}
  secretStoreRef: {{- toYaml . | nindent 4 }}
  {{- end }}
  target:
    name: {{ include "common.fullname" ( dict "root" $ "service" . "serviceName" "docker-registry" ) }}
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |-
          {{- include "application.secrets.externaldockerregistry" .content | nindent 10 }}
  data:
  {{- range $registryName, $conf := .content }}
  {{- with $conf.externalUsername }}
    - secretKey: {{ $registryName }}_username
      remoteRef:
        key: {{ $conf.externalUsername }}
  {{- end }}
  {{- with $conf.externalPassword }}
    - secretKey: {{ $registryName }}_password
      remoteRef:
        key: {{ $conf.externalPassword }}
  {{- end }}
  {{- with $conf.externalEmail }}
    - secretKey: {{ $registryName }}_email
      remoteRef:
        key: {{ $conf.externalEmail }}
  {{- end }}
  {{- with $conf.externalUrl }}
    - secretKey: {{ $registryName }}_url
      remoteRef:
        key: {{ $conf.externalUrl }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
