{{- with .Values.externalSecret }}
{{- if .enabled }}
{{- if ( or .data .dataFrom ) }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" . ) }}
  {{- include "common.metadata" ( dict "root" $ "service" . ) | nindent 2 }}
spec:
  {{- with .refreshInterval }}
  refreshInterval: {{ . }}
  {{- end }}
  {{- with .secretStoreRef }}
  secretStoreRef: {{- toYaml . | nindent 4 }}
  {{- end }}
  target:
    {{- if not ( hasKey ( default ( dict ) .target ) "name" ) }}
    name: {{ include "common.fullname" ( dict "root" $ "service" . "serviceName" "external-secret" ) }}
    {{- end }}
    {{- with .target }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .dataFrom }}
  dataFrom: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .data }}
  data: {{- include "common.dictToList" ( dict "keyName" "secretKey" "contents" . ) | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
