{{- $root := . -}}
{{- $values := .Values -}}
{{- range $serviceName, $serviceDefinition := $values.services }}
{{- if eq $serviceDefinition.enabled true }}
---
{{- if semverCompare ">=1.21.0" ( trimPrefix "v" $.Capabilities.KubeVersion.Version ) }}
apiVersion: policy/v1
{{- else -}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "common.fullname" ( dict "root" $root "service" $serviceDefinition "serviceName" $serviceName ) }}
  labels: {{- include "common.selectorLabels" ( dict "root" $root "service" $serviceDefinition "serviceName" $serviceName ) | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels: {{- include "common.selectorLabels" ( dict "root" $root "service" $serviceDefinition "serviceName" $serviceName ) | nindent 6 }}
{{- end }}
{{- end }}
