{{- with .Values.dockerregistry }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" . ) }}-dockerregistry
  {{- include "common.metadata" ( dict "root" $ "service" . ) | nindent 2 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "application.secrets.dockerregistry" .content | b64enc }}
{{- end }}
