{{- with .Values.dockerregistry }}
{{- if .enabled }}
{{- if not .external }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" . "serviceName" "dockerregistry" ) }}
  {{- include "common.metadata" ( dict "root" $ "service" . "serviceName" "dockerregistry" ) | nindent 2 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "application.secrets.dockerregistry" .content | b64enc }}
{{- end }}
{{- end }}
{{- end }}
