{{- with .Values.serviceAccount }}
{{- if .create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "application.serviceAccountName" ( $ ) }}
  {{- include "common.metadata" ( dict "root" $ "service" . ) | nindent 2 }}
{{- end }}
{{- end }}
